# Generated by Django 6.0.2 on 2026-04-28 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userprofile_profile_pic'),
        ('departments', '0002_channel_message_server_delete_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departments.server'),
        ),
    ]
