# Generated by Django 6.0.2 on 2026-04-30 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userprofile_profile_pic'),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.server'),
        ),
    ]
